### ISSUE TITLE
Visual bug-vizualizer is gigantic, only upper half on screen(4k monitor, no theme)

### ISSUE THREAD

**Issue by Armand3743** [Konsl/spicetify-ncs-visualizer#12]
![Screenshot (20)](https://github.com/Konsl/spicetify-ncs-visualizer/assets/130216701/46cf8f6a-4f34-4eed-88ee-b6a1d4997328)

**Comment by UP5-5** [comment]
I've also have the same problem, although I have a 1080p screen and using a theme.
![image](https://github.com/Konsl/spicetify-ncs-visualizer/assets/126914274/27c0800f-f54d-48c1-b1ed-8a6a1f12893c)

**Comment by UP5-5** [comment]
> I've also have the same problem, although I have a 1080p screen and using a theme. ![image](https://user-images.githubusercontent.com/126914274/281171088-27c0800f-f54d-48c1-b1ed-8a6a1f12893c.png)

I also just found out that this could be "fixed" if you zoom out by pressing together ctrl and -.
Not really a fix because the UI is too small for my liking.

https://github.com/Konsl/spicetify-ncs-visualizer/assets/126914274/36e27bb9-345f-49e6-998b-3832ca025859

**Comment by Konsl** [comment]
Does the last update solve your problem? I had a similar issue previously, but I didn't bother working on it as it only happened in very rare cases. Since I made some changes to the stylesheet, this stopped happening. If your problem still occurs to you, please let me know, otherwise just close the issue.

**Comment by UP5-5** [comment]
Sorry for the late response but I still have the same issue after updating.
