### ISSUE TITLE
Error: WebGL2 is not supported

### ISSUE THREAD

**Issue by notdevin-1** [Konsl/spicetify-ncs-visualizer#8]
Spotify for Windows
1.1.91.824.g07f1e963
Spicetify v2.24.2

Getting this error when opening the NCS Visualizer menu.
![image](https://github.com/Konsl/spicetify-ncs-visualizer/assets/80857978/da370f02-ae58-4619-be8c-0f42ca768a65)

**Comment by Konsl** [comment]
Could you give me some insight into Spotify's graphics configuration?

Please enable the DevTools using Spicetify, then right-click anywhere, click on `Show Chrome Tools`, then select `chrome://gpu` and send me a screenshot of the window.

**Comment by notdevin-1** [comment]
![image](https://github.com/Konsl/spicetify-ncs-visualizer/assets/80857978/3821a8f2-94c8-4d6d-8467-6d33d55d02a3)
![image](https://github.com/Konsl/spicetify-ncs-visualizer/assets/80857978/739e48d7-3748-49ef-9b77-9e1f0bd15d94)

**Comment by Konsl** [comment]
I did some investigation, together with another person who has a similar problem. There appears to be an issue with Chromium Embedded Framework on specific hardware. The relevant error message should be the part where it says `GPU rasterization should only be enabled on ...` This causes rasterization to be disabled, which is why NCS Visualizer doesn't work. As of now, we have not been able to resolve the issue, but we will let you know when we do.

**Comment by skrtpapapa** [comment]
> Spotify for Windows 1.1.91.824.g07f1e963 Spicetify v2.24.2
> 
> Getting this error when opening the NCS Visualizer menu. ![image](https://user-images.githubusercontent.com/80857978/274494210-da370f02-ae58-4619-be8c-0f42ca768a65.png)

UP

**Comment by notdevin-1** [comment]
Found a fix - reinstalled spotify with the version from the website, NOT Microsoft store version. from there run `spicetify backup apply` and you should be good to go
